
{   
let a = 10;
console.log(a);
// calling the function inside block
}
// Calling a function outside
// block throws an Error
console.log(a);
